protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property integer $id_post
 * @property string $created_date
 * @property string $title
 * @property string $description
 * @property string $image
 * @property integer $status
 * @property string $tags
 * @property string $keyword
 * @property string $url 
 * @property integer $views
 * @property integer $likes 
 * @property integer $id_user
 * @property integer $id_category
 */
class Post extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('created_date, title, description, image, status, id_user, id_category', 'required','on'=>'create'),
			array('title, description, status, id_user, id_category', 'required','on'=>'update'),
			array('status, views, likes, id_user, id_category', 'numerical', 'integerOnly'=>true),
			array('title, image, tags', 'length', 'max'=>255),
			array('keyword, url', 'length', 'max'=>140),
			array('title','unique'),

			//Validation Image
			array('image', 'required', 'on'=>'changeImage'),
			
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id_post, created_date, title, description, image, status, id_user, id_category', 'safe', 'on'=>'search'),
			);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'Member'=>array(self::BELONGS_TO,'Users','id_user'),
			'Category'=>array(self::BELONGS_TO,'Category','id_category'),
			);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_post' => 'Post ID',
			'created_date' => 'Date',
			'title' => 'Title',
			'description' => 'Description',
			'image' => 'Image',
			'status' => 'Status',
			'views' => 'Views',
			'likes' => 'Likes',
			'tags' => 'Tags',
			'keyword' => 'Keyword',												
			'id_user' => 'Posted By',
			'id_category' => 'Category',
			);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_post',$this->id_post);
		$criteria->compare('created_date',$this->created_date,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('image',$this->image,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('id_user',$this->id_user);
		$criteria->compare('id_category',$this->id_category);
		$criteria->order = "created_date DESC";

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			));
	}

	public function findPosts($UserID)
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_post',$UserID);
		$criteria->compare('created_date',$this->created_date,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description,true);
		$criteria->compare('image',$this->image,true);
		$criteria->compare('status',$this->status);
		$criteria->compare('id_user',$this->id_user);
		$criteria->compare('id_category',$this->id_category);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			));
	}	

	protected function beforeSave()
	{
		$this->created_date = date('Y-m-d', strtotime($this->created_date));
		return TRUE;
	}
	
	protected function afterFind()
	{
		$this->created_date = date('d-m-Y', strtotime($this->created_date));
		return TRUE;
	}

	public function status($a)
	{
		if($a==1)
			return "Enable";
		else 
			return "Disable";
	}	

	public static function getPortofolio(){
		$sql = "SELECT * FROM post WHERE status=1 AND id_category=1 ORDER BY id_post DESC LIMIT 6 ";
		$command = YII::app()->db->createCommand($sql);
		return $command->queryAll();
	}

	public static function getPortofolioFull(){
		$sql = "SELECT * FROM post WHERE status=1 ORDER BY views DESC";
		$command = YII::app()->db->createCommand($sql);
		return $command->queryAll();
	}	  

	public static function getPortofolioMy($data){
		$sql = "SELECT * FROM post WHERE status=1 AND id_user='".$data."' ORDER BY views DESC";
		$command = YII::app()->db->createCommand($sql);
		return $command->queryAll();
	}	   

	public function seo($title){
		return preg_replace('/[^a-z0-9_-]/i', '', strtolower(str_replace(' ', '-', trim($title))));
	}	

	public function thumbSmall($imagefile){
		$image = new EasyImage(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$imagefile);
		$image->scaleAndCrop(228, 151, EasyImage::RESIZE_AUTO);
		$image->save(Yii::getPathOfAlias('webroot').'/image/posting/small/'.$imagefile);
	}

	public function thumbMiddle($imagefile){
		$image = new EasyImage(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$imagefile);
		$image->scaleAndCrop(450, 300, EasyImage::RESIZE_AUTO);
		$image->save(Yii::getPathOfAlias('webroot').'/image/posting/middle/'.$imagefile);
	}	

	public function thumbBig($imagefile){
		$image = new EasyImage(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$imagefile);
		$mark = new EasyImage(Yii::getPathOfAlias('webroot').'/image/favicon/favicon.png');
		$image->watermark($mark, 20, 20);	
		$image->resize(1366, 1366);
		$image->save(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$imagefile);
	}		

}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			// 'postOnly + delete', // we only allow deletion via POST request
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('create','update','view','delete','admin','index','changeimage','publish','default','updateStats','data','remove','my'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==1',
				),
			array('allow',
				'actions'=>array('view','index','new','update','my','delete','changeimage','publish','default'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==2',
				),			
			array('deny',
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		if(Yii::app()->request->isAjaxRequest)
		{
			$this->renderPartial('view',array(
				'model'=>$this->loadModel($id),
				), false, true);
		}
		else
		{
			$this->render('view',array(
				'model'=>$this->loadModel($id),
				));
		}
	}
	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;
		$model->setScenario('create');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			$model->created_date = date('Y-m-d');
			$model->status=1;
			$model->id_user=YII::app()->user->id;
			
			if($model->url==""){
				$seotitle = Post::model()->seo($model->title);
				$model->url = $seotitle;
			}
			if(strlen(trim(CUploadedFile::getInstance($model,'image'))) > 0) 
			{ 
				$tmp=CUploadedFile::getInstance($model,'image'); 
				$model->image=$model->url.'.'.$tmp->extensionName; 
			}

			if($model->save()){
				//$userid,$description,$activityid,$type,$point,$status
				Activities::model()->my($model->id_user,$model->title,$model->id_post,2,3,2);

				if(strlen(trim($model->image)) > 0) {
					$tmp->saveAs(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$model->image);
					Post::model()->thumbSmall($model->image);
					Post::model()->thumbMiddle($model->image);
				}
				
				Yii::app()->user->setFlash('Success', '<i>'.$model->title.'</i> has been created.');
				$this->redirect(array('view','id'=>$model->id_post));
			}
		}

		$this->render('create',array(
			'model'=>$model,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		$model->setScenario('update');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->url==""){
				$seotitle = Post::model()->seo($model->title);
				$model->url = $seotitle;
			}	

			if($model->save()){
				//$userid,$description,$activityid,$type,$point,$status
				Activities::model()->my($model->id_user,$model->title,$model->id_post,6,1,10);

				Yii::app()->user->setFlash('Success', '<i>'.$model->title.'</i> has update.');
				$this->redirect(array('view','id'=>$model->id_post));
			}
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionRemove($id)
	{
		$model=$this->loadModel($id);
		$imageLocationOrginal = Yii::getPathOfAlias('webroot')."/image/posting/big/";
		$imageLocationSmall = Yii::getPathOfAlias('webroot')."/image/posting/small/";
		$imageLocationMiddle = Yii::getPathOfAlias('webroot')."/image/posting/middle/";
		if(empty($model->image)){
			$model->delete();
		}				
		if(!empty($model->image)){
			unlink($imageLocationOrginal.$model->image);
			unlink($imageLocationSmall.$model->image);
			unlink($imageLocationMiddle.$model->image);
		}	

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			Yii::app()->user->setFlash('Danger', 'Your post has remove.');
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		$imageLocationOrginal = Yii::getPathOfAlias('webroot')."/image/posting/big/";
		$imageLocationSmall = Yii::getPathOfAlias('webroot')."/image/posting/small/";
		$imageLocationMiddle = Yii::getPathOfAlias('webroot')."/image/posting/middle/";
		if(!empty($model->image)){
			unlink($imageLocationOrginal.$model->image);
			unlink($imageLocationSmall.$model->image);
			unlink($imageLocationMiddle.$model->image);
		}
		$model->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			Yii::app()->user->setFlash('danger', '<b>Successfully!</b> Your post has remove.');
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('my'));
	}	

	/**
	 * Lists all models.
	 */
	public function actionIndex($find='')
	{
		$criteria = new CDbCriteria();
		if(strlen($find)>0)
			$criteria->addSearchCondition('title', $find, true, 'OR');
		$criteria->addSearchCondition('description', $find, true, 'OR');
		$criteria->order = "created_date DESC";
		
		$dataProvider=new CActiveDataProvider('Post', array('criteria'=>$criteria));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}	

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Post $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='post-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionChangeImage($id)
	{
		$model=$this->loadModel($id);
		$model->setScenario('changeImage');
		if($model->id_user==Yii::app()->user->record->id_user){

			if(isset($_POST['Post']))
			{
				$model->attributes=$_POST['Post'];
				$tmp;
				if(strlen(trim(CUploadedFile::getInstance($model,'image'))) > 0) 
				{ 
					$tmp=CUploadedFile::getInstance($model,'image'); 
					$model->image=$model->url.'.'.$tmp->extensionName; 
				}

				if($model->save()){
					if(strlen(trim($model->image)) > 0) 
					$tmp->saveAs(Yii::getPathOfAlias('webroot').'/image/posting/big/'.$model->image);
					Post::model()->thumbSmall($model->image);
					Post::model()->thumbMiddle($model->image);
					Yii::app()->user->setFlash('Success', 'Image '.$model->title.' has been update.');
					$this->redirect(array('view','id'=>$model->id_post));
				}
			}

			$this->render('image',array(
				'model'=>$model,
				));

		}else{
			throw new CHttpException(403,'You not authorized to this perfom.');
		}
	}	

	// public function actionChangeImage($id)
	// {
	// 	$model=$this->loadModel($id);
	// 	$model->setScenario('changeImage');
	// 	if(isset($_POST['Post']))
	// 	{
	// 		$model->attributes=$_POST['Post'];

	// 		$lokasi = Yii::getPathOfAlias('webroot')."/image/posting/big/";
	// 		$posting = Post::model()->find("id_post = ".$model->id_post);
	// 		if(!empty($posting->image)){
	// 			if(empty($posting->image)){
	// 				unlink($lokasi.$posting->image);
	// 			}else{
	// 			}
	// 		}

	// 		$imageInfo = CUploadedFile::getInstance($model,'image');
	// 		$seotitle = Post::model()->seo($model->title);
	// 		$tmp=CUploadedFile::getInstance($model,'image'); 
	// 		$model->image=$seotitle.'.'.$tmp->extensionName;			
	// 		$model->image=$model->image;   			

	// 		if($model->save()){
	// 			if(strlen(trim($model->image)) > 0){
	// 				$imageInfo->saveAs($lokasi.$model->image); 
	// 				Post::model()->thumbSmall($model->image);
	// 				Post::model()->thumbMiddle($model->image);
	// 			}
	// 			$this->redirect(array('view','id'=>$model->id_post));
	// 		}
	// 	}

	// 	$this->render('image',array(
	// 		'model'=>$model,
	// 		));
	// }		

	public function actionNew()
	{
		$model=new Post;
		$model->setScenario('create');

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			$model->created_date = date('Y-m-d');
			$model->status=1;
			$model->id_user=YII::app()->user->id;
			
			//$userid,$description,$activityid,$type,$point,$status
			Activities::model()->my($model->id_user,$model->title,$model->id_post,2,3,2);
			
			if($model->url==""){
				$seotitle = Post::model()->seo($model->title);

protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<ul class="nav nav-tabs tabs">
			<li class="active tab"><a href="#post" data-toggle="tab" aria-expanded="false" class="active"><span class="visible-xs"><i class="fa fa-bar-chart-o"></i></span> 
				<span class="hidden-xs">Post</span></a></li>

				<li class="tab"><a href="#settings" data-toggle="tab" aria-expanded="false"><span class="visible-xs"><i class="fa fa-bar-chart-o"></i></span> 
					<span class="hidden-xs">Settings</span></a></li>

					<div class="indicator">
					</div>
				</ul>
			</div>
		</div>

		<div class="row">
			<div class="col-lg-12">
				<div class="tab-content profile-tab-content">

					<?php $form=$this->beginWidget('CActiveForm', array(
						'id'=>'post-form',
						'enableAjaxValidation'=>false,
						'enableClientValidation' => true,
						'clientOptions' => array(
							'validateOnSubmit' => true,
							),
						'errorMessageCssClass' => 'label label-danger',
						'htmlOptions' => array('enctype' => 'multipart/form-data','autocomplete'=>'off'),
						)); ?>

						<!-- END: TAB 1 -->
						<div class="tab-pane active" id="post">
							<div class="row">
								<div class="col-md-12">
									<!-- Stats : Todak -->

									<div class="form-normal form-horizontal clearfix">
										<div class="col-lg-12 col-md-12"> 


											<?php echo $form->errorSummary($model, null, null, array('class' => 'alert alert-warning')); ?>

											<div class="form-group">
												<div class="col-sm-12">
													<?php echo $form->error($model,'title'); ?>
													<?php echo $form->textField($model,'title',array('class'=>'form-control input-lg','placeHolder'=>'Title')); ?>
												</div>
											</div>  


											<div class="form-group">
												<div class="col-sm-12">
													<?php echo $form->error($model,'description'); ?>
													<?php echo $form->textArea($model,'description',array('class'=>'summernote','placeHolder'=>'Description')); ?>
												</div>
											</div>  


											<div class="form-group">
												<div class="col-sm-6">
													<?php echo $form->error($model,'image'); ?>
													<?php echo $form->fileField($model,'image',array('class'=>'btn btn-default waves-effect m-b-5')); ?>
												</div>
												<div class="col-sm-6">
													<?php echo $form->error($model,'id_category'); ?>
													<?php 
													echo $form->dropDownList($model, "id_category",
														CHtml::listData(Category::model()->findAll(array('condition'=>'status=1')),
															'id_category', 'name'
															),
														array("empty"=>"-- Category --", 'class'=>'select2 form-control')
														); 
														?> 
													</div>
												</div>  


												<div class="form-group">
													<div class="col-md-12">  
														<?php echo CHtml::submitButton($model->isNewRecord ? 'Publish' : 'Update', array('class' => 'btn btn-info pull-right waves-light')); ?>
													</div>
												</div>

											</div></div><!-- form -->

										</div>
									</div>
								</div>
								<!-- END: TAB 1 -->

								<!-- END: TAB 2 -->
								<div class="tab-pane active" id="settings">
									<div class="row">
										<div class="col-md-12">
											<!-- Stats : Week -->

											<div class="form-normal form-horizontal clearfix">
												<div class="col-lg-12 col-md-12"> 

													<?php echo $form->errorSummary($model, null, null, array('class' => 'alert alert-warning')); ?>

													<div class="form-group">
														<div class="col-sm-6">
															<?php echo $form->error($model,'tags'); ?>
															<?php echo $form->textField($model,'tags',array('id'=>'tags')); ?>
														</div>

														<div class="col-sm-6">
															<?php echo $form->error($model,'keyword'); ?>
															<?php echo $form->textArea($model,'keyword',array('class'=>'form-control','placeHolder'=>'Short Description')); ?>
														</div>
													</div>  	

													<div class="form-group">
														<div class="col-sm-12">
															<?php echo $form->error($model,'url'); ?>
															<?php echo $form->textField($model,'url',array('class'=>'form-control','placeHolder'=>'Custom URL')); ?>
														</div>
													</div>  																	

													<div class="form-group">
														<div class="col-md-12">  
															<?php echo CHtml::submitButton($model->isNewRecord ? 'Publish' : 'Update', array('class' => 'btn btn-info pull-right waves-light')); ?>
														</div>
													</div>

													<?php $this->endWidget(); ?>

												</div></div><!-- form -->

											</div>
										</div>
									</div>
									<!-- END: TAB 2 -->

								</div>
							</div>
						</div>
						

protected/views/post/_form_image.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="form-normal form-horizontal clearfix">
	<div class="col-md-9"> 

		<?php $form=$this->beginWidget('CActiveForm', array(
			'id'=>'post-form',
			'enableAjaxValidation'=>false,
			'enableClientValidation'=>true,
			'clientOptions'=>array('validateOnSubmit'=>true),
			'htmlOptions' => array('enctype' => 'multipart/form-data','autocomplete'=>'off'),
			)); ?>

			<?php echo $form->errorSummary($model, null, null, array('class' => 'alert alert-warning')); ?>
			<?php if(!$model->image==""): ?>
			<div class="form-group">
				<div class="col-sm-4 control-label">
				</div>   
				<div class="col-sm-8">
					<center>
						<div class="item">
							<a href='<?php echo Yii::app()->baseUrl; ?>/image/posting/big/<?php echo $model->image; ?>'><img src='<?php echo Yii::app()->baseUrl; ?>/image/posting/small/<?php echo $model->image; ?>' alt="Post Image"></a>
						</div>
					</center>
				</div>
			</div>
			<?php endif; ?>  			

			<div class="form-group">
				<div class="col-sm-4 control-label">
					<?php echo $form->labelEx($model,'image'); ?>
				</div>   
				<div class="col-sm-8">
					<?php echo $form->error($model,'image'); ?>
					<?php echo $form->fileField($model,'image',array('id'=>'fileupload','class'=>'btn btn-info')); ?>
				</div>
			</div>  

		</div>

	</div><!-- form -->

	<div class="panel-footer text-right">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Submit' : 'Edit', array('class' => 'btn btn-info btn-flat pull-right')); ?>
		<BR><BR>
		</div>

		<?php $this->endWidget(); ?>

protected/views/post/admin.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Manage',
	);

$this->pageTitle='Manage Post';

// Yii::app()->clientScript->registerScript('ajaxupdate', "
// $('#post-grid a.ajaxupdate').live('click', function() {
//         $.fn.yiiGridView.update('post-grid', {
//                 type: 'POST',
//                 url: $(this).attr('href'),
//                 success: function() {
//                         $.fn.yiiGridView.update('post-grid');
//                 }
//         });
//         return false;
// });
// ");
?>

<span class="visible-xs">

	<?php echo CHtml::link('<i class="fa fa-plus"></i>',
		array('create'),
		array('class' => 'btn btn-primary btn-md','title'=>'Add Post'));
		?>

		<?php echo CHtml::link('<i class="fa fa-tasks"></i>',
			array('index'),
			array('class' => 'btn btn-primary btn-md','title'=>'Posts List'));
			?>

			<?php echo CHtml::link('<i class="fa fa-tags"></i>',
				array('category/admin'),
				array('class' => 'btn btn-primary btn-md','title'=>'Category List'));
				?>

			</span> 

			<span class="hidden-xs">

				<?php echo CHtml::link('New',
					array('create'),
					array('class' => 'btn btn-primary btn-flat','title'=>'New Post'));
					?>

					<?php echo CHtml::link('List',
						array('index'),
						array('class' => 'btn btn-primary btn-flat','title'=>'Posts List'));
						?>

						<?php echo CHtml::link('Category',
							array('category/admin'),
							array('class' => 'btn btn-primary btn-md','title'=>'Category List'));
							?>

						</span>


						<HR>

							<?php $this->widget('zii.widgets.grid.CGridView', array(
								'id'=>'post-grid',
								'dataProvider'=>$model->search(),
								'filter'=>$model,
								'itemsCssClass' => 'table-responsive table table-striped table-hover table-vcenter',
								'columns'=>array(

									array(
										'header'=>'No',
										'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
										'htmlOptions'=>array('width'=>'10px', 
											'style' => 'text-align: center;')),

									array(
										'name'=>'id_user',
										'value'=>'$data->Member->first_name ." ".$data->Member->last_name'
										),									

									'created_date',
									'title',

									array(	
										'name'=>'status',
										'filter'=>array('0'=>'Disable','1'=>'Enable'),
										'value'=>'Post::model()->status($data->status)',
										),

									// array(
									// 	'name'=>'status',
									// 	'type'=>'raw',
									// 	'value'=>'CHtml::link(Post::model()->status($data->status), array("updateStats", "id"=>$data->id_post), array("class"=>"ajaxupdate"));',
									// ),									

									array(
										'class'=>'CButtonColumn',
										'template'=>'{view}{delete}',
										'buttons'=>array(
											'view'=>
											array(
												'url'=>'Yii::app()->createUrl("post/view", array("id"=>$data->id_post))',
												'options'=>array(
													'ajax'=>array(
														'type'=>'POST',
														'url'=>"js:$(this).attr('href')",
														'success'=>'function(data) { $("#viewModal .modal-body p").html(data); $("#viewModal").modal(); }'
														),
													),
												),
											),
										),

									),
									)); ?>


									<!-- Modal -->
									<div class="modal fade" id="viewModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
										<div class="modal-dialog modal-lg">
											<div class="modal-content">
												<!-- Popup Header -->
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
													<h4 class="modal-title"><strong>View</strong> Post</h4>
												</div>
												<!-- Popup Content -->
												<div class="modal-body">
													<p>Details</p>
												</div>
												<!-- Popup Footer -->
												<div class="modal-footer">
													<BR>
														<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
													</div>
												</div>
											</div>
										</div>

protected/views/post/create.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'New',
	);

	$this->pageTitle='New Post';
	?>

	<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>